#spring.application.name=paofresquim

# ============================================================
# Datasource - MySQL
# ============================================================
spring.datasource.url=jdbc:mysql://localhost:3306/paofresquim
spring.datasource.username=root
spring.datasource.password=N@sciment0
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================================================
# JPA / Hibernate
# ============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ============================================================
# Servidor
# ============================================================
server.port=8080

# ============================================================
# API SMS GATEWAY MASTER
# ============================================================
sms.api.key=sk_live_SEU_TOKEN_AQUI
sms.api.url=https://api.sms-gate.app/3rdparty/v1/message

# ============================================================
# E-mail RESEND API
# ============================================================
email.api.key=re_c9XC16SU_MXeBNmmEWaefiomd3tDeVRSF
email.from=Pão Fresquim <onboarding@resend.dev>
email.api.url=https://api.resend.com/emails

# ============================================================
# WHATSAPP RESEND API
# ============================================================
evolution.api.url= https://apps-evolution-api.ymqjmy.easypanel.host
evolution.api.key= 60A64C71491C-4F7E-858A-986006FF1AB7
evolution.dispatch.path=/message/sendText/Alyssson
